name: build-qt-program

jobs:
  build-qt-program:
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install Qt
        run: choco install -y --no-progress qt5-default
      - name: Build program
        run: |
          $xmlResult = Select-Xml -Path $env:APPDATA\QtProject\qtcreator\qtversion.xml -XPath "/qtcreator/data/valuemap/value[@key='QMakePath']"
          $Qtmake = $xmlResult.Node.InnerText
          & $Qtmake src\LittleTimer.pro
          make
